[tool.poetry]
name = "multi-agentic-ai-system-framework"
version = "0.1.0"
description = "A framework for multi-agentic AI systems."
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.12"